/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesItemIdRouteImport } from './routes/series/$itemId'
import { Route as PlayerItemIdRouteImport } from './routes/player/$itemId'
import { Route as ArtistItemIdRouteImport } from './routes/artist/$itemId'
import { Route as AlbumItemIdRouteImport } from './routes/album/$itemId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesItemIdRoute = SeriesItemIdRouteImport.update({
  id: '/series/$itemId',
  path: '/series/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerItemIdRoute = PlayerItemIdRouteImport.update({
  id: '/player/$itemId',
  path: '/player/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistItemIdRoute = ArtistItemIdRouteImport.update({
  id: '/artist/$itemId',
  path: '/artist/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumItemIdRoute = AlbumItemIdRouteImport.update({
  id: '/album/$itemId',
  path: '/album/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/album/$itemId': typeof AlbumItemIdRoute
  '/artist/$itemId': typeof ArtistItemIdRoute
  '/player/$itemId': typeof PlayerItemIdRoute
  '/series/$itemId': typeof SeriesItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/album/$itemId': typeof AlbumItemIdRoute
  '/artist/$itemId': typeof ArtistItemIdRoute
  '/player/$itemId': typeof PlayerItemIdRoute
  '/series/$itemId': typeof SeriesItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/album/$itemId': typeof AlbumItemIdRoute
  '/artist/$itemId': typeof ArtistItemIdRoute
  '/player/$itemId': typeof PlayerItemIdRoute
  '/series/$itemId': typeof SeriesItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/album/$itemId'
    | '/artist/$itemId'
    | '/player/$itemId'
    | '/series/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/album/$itemId'
    | '/artist/$itemId'
    | '/player/$itemId'
    | '/series/$itemId'
  id:
    | '__root__'
    | '/'
    | '/album/$itemId'
    | '/artist/$itemId'
    | '/player/$itemId'
    | '/series/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlbumItemIdRoute: typeof AlbumItemIdRoute
  ArtistItemIdRoute: typeof ArtistItemIdRoute
  PlayerItemIdRoute: typeof PlayerItemIdRoute
  SeriesItemIdRoute: typeof SeriesItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series/$itemId': {
      id: '/series/$itemId'
      path: '/series/$itemId'
      fullPath: '/series/$itemId'
      preLoaderRoute: typeof SeriesItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$itemId': {
      id: '/player/$itemId'
      path: '/player/$itemId'
      fullPath: '/player/$itemId'
      preLoaderRoute: typeof PlayerItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$itemId': {
      id: '/artist/$itemId'
      path: '/artist/$itemId'
      fullPath: '/artist/$itemId'
      preLoaderRoute: typeof ArtistItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$itemId': {
      id: '/album/$itemId'
      path: '/album/$itemId'
      fullPath: '/album/$itemId'
      preLoaderRoute: typeof AlbumItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlbumItemIdRoute: AlbumItemIdRoute,
  ArtistItemIdRoute: ArtistItemIdRoute,
  PlayerItemIdRoute: PlayerItemIdRoute,
  SeriesItemIdRoute: SeriesItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
