name: React Doctor

on:
  pull_request:
  push:
    branches: [master]

permissions:
  contents: read
  pull-requests: write # required to post PR comments

jobs:
  react-doctor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # required for `diff`
      - uses: millionco/react-doctor@8244f1f28fd405d5a3d192887df3790d7b3f9179
        with:
          diff: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
